// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejegphkdbtkzvndosxva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqZWdwaGtkYnRrenZuZG9zeHZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MjAxMjUsImV4cCI6MjA2OTk5NjEyNX0._cbCbenBy8UPD_fLleJ7bYmoCbNyRwO5QFsEOZExFe4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});